apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-api
  namespace: api-team1
spec:
  destination:
    namespace: api-team1
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/msakho/rhoam-ci-cd-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true