apiVersion: v1
kind: Secret
metadata:
  name: rhoam-t2robot-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: rhoam-bt
  server: https://api.bitmarck-lab3.006z.p1.openshiftapps.com:6443
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6InlWZ2NTcGtudXRTWU96X1p0T3JvSTRqRzFNQy1Lbnpfc2hKZWtsZUU0S2MifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcGktdGVhbTIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoidDJyb2JvdC10b2tlbi1ra2ZmcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJ0MnJvYm90Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZDNjYTlhZGUtOWIwZC00YjZiLTg3NWYtNjFlY2ZjMzk4ZDRiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFwaS10ZWFtMjp0MnJvYm90In0.HWcIWY3ku8GwdtLM1zuUlTjYnTlV-c3ETAL-LTFguSeINEWSWI-udOvllIt4mkNCJ1pcSaTKgSZ8kzFe3bwNP9Xzr-MnWo-c8CYBe5vXNAWIvzOAUauUf7lH57qIZQjSkkNKJbvGa8Qs9gmF8CvmOnvZqjez1In-PZ_TbI--0YI-TF45XxPi_BkPWTAcUG1AtOT8px3gdm8VVvjw_rEYmGQfG1mw0vEwSuoSp4YaAgR_hGDKRW3ayw_WnVFqy7qhxGUu4SIeASeEAVOqZIPHYFUFPgGKcvzt7ytxG72XgaKm6qmuihN5bjxOnxPcoZcT4E-tVPU4QkiCvSrY-opfqClORG7AuyuC4YMcvPhDBYlfQtB5KrsTb1FyKZ5I1VnSMn1YSlWRFpuLv5mbO2QcxnZcj08zUfx0tau3v_IjQ0YUJHrYkv9mz5ZSnrwWrb3Zl5s7cAUDsmyB8yEiZDqHa1QnTe4ric4j-DM2KFtLFf9a6xZ-68PYmIBTkli0K195O3t6dVd4j_6P3Bz2Tau9jnA4rE8jeJEy8jio6I_X64ig5UX41EinyGqUwNC2HmmHoq_8b7SSO2UOa94oow1652PamGxpqh03-C2Oe6fLJyWchua_kvB6vvRuFyErYDcziGbrk59ZD0bvcjhV214MHQTifuvC4VnONDngc9D_Yr0",
      "tlsClientConfig": {
        "insecure": true     
      }
    }